# SPDX-License-Identifier: MIT-0
---
- name: Update & packages / dist upgrade
  ansible.builtin.apt:
    update_cache: true
    upgrade: "dist"

- name: Clean & Purge apt packages
  ansible.builtin.apt:
    clean: true
    autoremove: true
  changed_when: false

- name: Docker prune everything
  community.docker.docker_prune:
    builder_cache_all: true
    containers: true
    images: true
    images_filters:
      dangling: false
    networks: true

- name: Crowdsec hub packages update
  ansible.builtin.command:
    cmd: "cscli hub update"
  changed_when: false

- name: Crowdsec hub packages upgrade
  ansible.builtin.command:
    cmd: "cscli collections upgrade --all"
  register: maintenance_crowdsec_upgrade
  changed_when: "'upgraded' in maintenance_crowdsec_upgrade.stdout or 'updated' in maintenance_crowdsec_upgrade.stdout"
  notify: Reload Crowdsec

- name: Run Kopia full maintenance
  ansible.builtin.command:
    cmd: >
      docker run --rm --hostname="{{ kopia_client_hostname }}"
      -v "{{ kopia_root_dir }}/config:/app/config"
      -v "{{ kopia_root_dir }}/cache:/app/cache:rw"
      -e KOPIA_PASSWORD="{{ kopia_password }}"
      -e KOPIA_CONFIG_PATH="{{ kopia_config_path }}"
      {{ kopia_app_image }}:{{ kopia_app_image_tag }}
      maintenance run --full
  register: maintenance_kopia_full
  no_log: true
  changed_when: "'Finished' in maintenance_kopia_full.stdout"
  when: target_env != 'dev'

- name: Verify if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: maintenance_reboot_required
  tags: [always]

- name: Notify via webhook if reboot is required
  ansible.builtin.uri:
    url: "{{ maintenance_discord_webhook_url }}"
    method: "POST"
    body_format: json
    body: { "content": "Reboot on {{ inventory_hostname }} is required", "username": "SENTINEL" }
    status_code: 204
  when:
    - maintenance_reboot_required.stat.exists
    - not maintenance_auto_reboot | bool
    - target_env != 'dev'

- name: Determine if reboot is needed
  ansible.builtin.set_fact:
    maintenance_should_reboot: "{{ maintenance_reboot_required.stat.exists | bool and maintenance_auto_reboot | bool or maintenance_force_reboot | bool }}"
  tags: [always]

- name: Stop all docker containers properly
  ansible.builtin.shell: |
    set -o pipefail
    docker ps -q | xargs -r docker stop
  args:
    executable: /bin/bash
  register: maintenance_stop_docker_containers
  when: maintenance_should_reboot
  changed_when: maintenance_stop_docker_containers.stdout | length > 0

- name: Reboot the server
  ansible.builtin.reboot:
    msg: "Reboot by Ansible (maintenance role - not in cicd)"
    pre_reboot_delay: 10
    reboot_timeout: 600
    test_command: whoami
  tags: [reboot]
  when:
    - maintenance_should_reboot | bool
    - not maintenance_with_cicd | bool

- name: Reboot the server (CI Mode - Self-Hosted Runner)
  ansible.builtin.command: "shutdown -r +1 'Reboot orchestré par la CI'"
  when:
    - maintenance_should_reboot | bool
    - maintenance_with_cicd | bool
  changed_when: false
  tags: [reboot]

- name: Verify if all containers are healthy (No unhealthy, no starting)
  ansible.builtin.shell: |
    set -o pipefail
    docker ps --format '{{ '{{' }} .Status {{ '}}' }}' | grep -E '\(unhealthy\)|\(starting\)' | wc -l
  args:
    executable: /bin/bash
  register: maintenance_containers_not_ready_count
  until: maintenance_containers_not_ready_count.stdout == "0"
  delay: 30
  retries: 10
  failed_when: maintenance_containers_not_ready_count.stdout != "0"
  when: maintenance_should_reboot | bool or 'healthcheck' in ansible_run_tags
  changed_when: false
  tags: [healthcheck]

- name: Notify when reboot is success via webhook
  ansible.builtin.uri:
    url: "{{ maintenance_discord_webhook_url }}"
    method: "POST"
    body_format: json
    body: { "content": "✅ {{ inventory_hostname }} is up and all Docker containers are healthy", "username": "SENTINEL" }
    status_code: 204
  when:
    - maintenance_should_reboot | bool or 'healthcheck' in ansible_run_tags
    - not ansible_check_mode
    - target_env != 'dev'
  tags: [healthcheck]
