---
vaultwarden_stack_state: "present" # present | stopped | absent

vaultwarden_app_name: "vaultwarden"
vaultwarden_app_image: "vaultwarden/server"
vaultwarden_app_image_tag: "1.37.1-alpine"
vaultwarden_traefik_domain: "services.codeterm.fr"
vaultwarden_root_dir: "{{ project_root_dir }}/{{ vaultwarden_app_name }}"
vaultwarden_web_url: "{{ vaultwarden_app_name }}.{{ vaultwarden_traefik_domain }}"
vaultwarden_reverse_proxy_network: "{{ traefik_network }}"
vaultwarden_server_port: "80"

# Env vars
vaultwarden_domain: "https://{{ vaultwarden_web_url }}"
vaultwarden_signups_allowed: false
vaultwarden_signups_verify: true
vaultwarden_invitations_allowed: true
vaultwarden_admin_token: "{{ vault_vaultwarden_admin_token }}"

vaultwarden_db_url: "data/db.sqlite3"
vaultwarden_websocket_enabled: true

vaultwarden_push_enabled: true
vaultwarden_push_installation_id: "{{ vault_vaultwarden_push_installation_id | default('') }}"
vaultwarden_push_installation_key: "{{ vault_vaultwarden_push_installation_key | default('') }}"


vaultwarden_smtp_enabled: true
vaultwarden_smtp_host: "mail.infomaniak.com"
vaultwarden_smtp_from: "{{ vault_vaultwarden_smtp_username | default('') }}"
vaultwarden_smtp_from_name: "Vaultwarden"
vaultwarden_smtp_security: "starttls"
vaultwarden_smtp_port: 587
vaultwarden_smtp_username: "{{ vault_vaultwarden_smtp_username | default('') }}"
vaultwarden_smtp_password: "{{ vault_vaultwarden_smtp_password | default('') }}"


vaultwarden_log_level: "info"

# System User / Group
vaultwarden_group_name: "vaultwarden"
vaultwarden_user_name: "vaultwarden"
vaultwarden_group_id: null
vaultwarden_user_id: null

# Resources
vaultwarden_ram_reservation: "256M"
vaultwarden_ram_limit: "512M"

# Healthcheck
vaultwarden_healthcheck_enabled: false
vaultwarden_healthcheck_test: '["CMD", "/healthcheck.sh"]'
vaultwarden_healthcheck_interval: "30s"
vaultwarden_healthcheck_timeout: "10s"
vaultwarden_healthcheck_retries: 3
vaultwarden_healthcheck_start_period: "20s"
