---
portainer_stack_state: "present" # present | stopped | absent
portainer_app_image: ""
portainer_app_image_tag: ""
portainer_admin_password_hash: "{{ vault_portainer_admin_password_hash }}"

portainer_role_name: "portainer"
portainer_root_dir: "{{ project_root_dir }}/{{ portainer_role_name }}"
portainer_reverse_proxy_network: "{{ traefik_network }}"
portainer_web_url: "{{ portainer_role_name }}.{{ traefik_domain }}"
