---
project_root_dir: "/opt/talos"

target_user: "sentinel"
target_ssh_port: 8888
target_ssh_pubkey: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
target_password_hash: "{{ vault_target_password_hash }}"

remove_default_user: true
common_default_user: "debian"

docker_users:
  - "{{ target_user }}"

common_docker_group_name: "docker"
docker_install_compose_plugin: true

http_port: 80
https_port: 443
tailscale_p2p_port: 41641

smtp_host: "smtp.eu.mailgun.org"
smtp_user: "{{ vault_smtp_user }}"
smtp_password: "{{ vault_smtp_password }}"
smtp_port: 587

traefik_network: "talos_network"

kopia_state: present
kopia_service_name: "kopia"
kopia_image_tag: "0.22.3"
kopia_timezone: "Europe/Paris"
kopia_backup_agent_name: "kopia-backup-agent"

kopia_password: "{{ vault_kopia_password }}"
kopia_repository_username: "{{ vault_kopia_repository_username }}"

kopia_s3_endpoint_url: "ec05260ab81ba0bdf549ac94b31821c0.eu.r2.cloudflarestorage.com"
kopia_s3_access_key_id: "{{ vault_kopia_s3_access_key_id }}"
kopia_s3_access_key_secret: "{{ vault_kopia_s3_access_key_secret }}"

kopia_root_dir: "/opt/talos/kopia"

kopia_local_dump_dir: "{{ kopia_root_dir }}/dumps_sql"
kopia_scripts_dir: "{{ kopia_root_dir }}/scripts"

kopia_config_path: "/app/config/repository.config"

kopia_folders_to_save:
  - "/opt/talos"

kopia_container_suffix: "-db"
kopia_cleanup_sqldumps_after_backup: true

kopia_policy_keep_daily: 7
kopia_policy_keep_weekly: 4
kopia_policy_keep_monthly: 6

kopia_policy_compression: "zstd"

kopia_backup_execution_timer: "*-*-* 03:00:00"

kopia_email_report_enabled: true
kopia_email_report_to: "remydubois411@gmail.com"
kopia_email_from: "talos-backup@remydubois.fr"
kopia_smtp_host: "{{ smtp_host }}"
kopia_smtp_port: "{{ smtp_port }}"
kopia_smtp_username: "{{ smtp_user }}"
kopia_smtp_password: "{{ smtp_password }}"

kopia_traefik_enabled: true
kopia_traefik_network: "{{ traefik_network }}"
kopia_traefik_domain: "kopia.{{ traefik_domain }}"
kopia_web_port_expose: 51515
kopia_traefik_entrypoints: "websecure"
kopia_traefik_certresolver: "letsencrypt-dns"
kopia_traefik_middlewares: "secHeaders@file,tailscaleOnly@file"

runner_dir: "/opt/talos/github-runner"
runner_user: "github-runner"
github_account: "ReDxOps"
github_repo: "talos-ansible"
access_token: "{{ vault_github_pat }}"
runner_labels: [ "{{ target_env | default('dev') }}" ]
