---

- name: Create application directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "1000"
    group: "1000"
  loop:
    - "{{ ark_root_dir }}"
    - "{{ ark_root_dir }}/{{ ark_fjordur_name }}"
    - "{{ ark_root_dir }}/{{ ark_fjordur_backup_directory_name }}"
    - "{{ ark_root_dir }}/{{ ark_cluster_directory }}"

- name: Copy docker-compose template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ ark_root_dir }}/docker-compose.yml"
    mode: '0644'
  register: compose_file_status

- name: Check GameUserSettings.ini
  community.general.ini_file: 
    path: "{{ ark_root_dir }}/{{ ark_fjordur_name }}/GameUserSettings.ini"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    owner: "1000"
    group: "1000"
    mode: "0644"
    create: yes
  loop: "{{ ark_game_user_settings }}" 
  check_mode: yes
  register: game_user_settings_status

- name: Check Game.ini
  community.general.ini_file: 
    path: "{{ ark_root_dir }}/{{ ark_fjordur_name }}/Game.ini"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    owner: "1000"
    group: "1000"
    mode: "0644"
    create: yes
  loop: "{{ ark_game_settings }}" 
  check_mode: yes
  register: game_settings_status

- name: Stop application stack
  community.docker.docker_compose_v2:
    project_src: "{{ ark_root_dir }}"
    state: stopped
  when: compose_file_status.changed or game_user_settings_status.changed or game_settings_status.changed

- name: Modify GameUserSettings.ini
  community.general.ini_file: 
    path: "{{ ark_root_dir }}/{{ ark_fjordur_name }}/GameUserSettings.ini"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    owner: "1000"
    group: "1000"
    mode: "0644"
    create: yes
  loop: "{{ ark_game_user_settings }}" 
  when: game_user_settings_status.changed

- name: Modify Game.ini
  community.general.ini_file: 
    path: "{{ ark_root_dir }}/{{ ark_fjordur_name }}/Game.ini"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    owner: "1000"
    group: "1000"
    mode: "0644"
    create: yes
  loop: "{{ ark_game_settings }}" 
  when: game_settings_status.changed

- name: Start docker-compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ ark_root_dir }}"
    state: present
    pull: always
