---
invoiceninja_hestia_stack_state: "present" # present | stopped | absent
invoiceninja_hestia_app_image: ""
invoiceninja_hestia_app_image_tag: ""
invoiceninja_hestia_mariadb_image: ""
invoiceninja_hestia_mariadb_image_tag: ""
invoiceninja_hestia_redis_image: ""
invoiceninja_hestia_redis_image_tag: ""
invoiceninja_hestia_nginx_image: ""
invoiceninja_hestia_nginx_image_tag: ""
invoiceninja_hestia_role_name: "invoiceninja-hestia"
invoiceninja_hestia_root_dir: "{{ project_root_dir }}/{{ invoiceninja_hestia_role_name }}"

invoiceninja_hestia_web_url: "facturation.hestialoyalty.fr"
invoiceninja_hestia_app_key: "{{ vault_invoiceninja_hestia_app_key }}"
invoiceninja_hestia_app_env: "production"
invoiceninja_hestia_app_debug: false

invoiceninja_hestia_db_port: 3306
invoiceninja_hestia_db_name: "invoiceninja_hestia_db"
invoiceninja_hestia_db_user: "{{ vault_invoiceninja_hestia_db_user }}"
invoiceninja_hestia_db_password: "{{ vault_invoiceninja_hestia_db_password }}"

invoiceninja_hestia_initial_user_email: "{{ vault_invoiceninja_hestia_initial_user_email }}"
invoiceninja_hestia_initial_user_password: "{{ vault_invoiceninja_hestia_initial_user_password }}"

invoiceninja_hestia_smtp_mailer: "mailgun"
invoiceninja_hestia_smtp_domain: "hestialoyalty.fr"
invoiceninja_hestia_smtp_api_key: "{{ vault_invoiceninja_hestia_smtp_api_key }}"
invoiceninja_hestia_smtp_endpoint_url: "api.eu.mailgun.net"
invoiceninja_hestia_smtp_send_from_address: "facturation@hestialoyalty.fr"
invoiceninja_hestia_smtp_send_from_name: "Facturation Hestia Studio"

invoiceninja_hestia_reverse_proxy_network: "{{ traefik_network }}"
