---

- name: Create application directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ wikijs_root_dir }}"
    - "{{ wikijs_root_dir }}/data"
    - "{{ wikijs_root_dir }}/wiki-uploads"
    - "{{ wikijs_root_dir }}/db_data"

- name: Copy docker-compose template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ wikijs_root_dir }}/docker-compose.yml"
    mode: '0644'

- name: Start docker-compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ wikijs_root_dir }}"
    state: present
    pull: always
