---
- name: Modify GameUserSettings.ini
  community.general.ini_file:
    path: "{{ ark_fjordur_config_path }}/GameUserSettings.ini"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    owner: "1000"
    group: "1000"
    mode: "0644"
    create: true
  loop: "{{ ark_game_user_settings }}"

- name: Modify Game.ini
  community.general.ini_file:
    path: "{{ ark_fjordur_config_path }}/Game.ini"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    owner: "1000"
    group: "1000"
    mode: "0644"
    create: true
  loop: "{{ ark_game_settings }}"

- name: Modify Custom Loots in Game.ini (blockinfile)
  ansible.builtin.blockinfile:
    path: "{{ ark_fjordur_config_path }}/Game.ini"
    marker: "; {mark} ANSIBLE MANAGED LOOT DROPS"
    block: "{{ ark_custom_loots }}"
    owner: "1000"
    group: "1000"
    mode: "0644"
    create: true
