---
invoiceninja_image_tag: "5.13"
invoiceninja_mariadb_image_tag: "11.8"
invoiceninja_redis_image_tag: "8.6.2-alpine"
invoiceninja_nginx_image_tag: "1.29.8"
invoiceninja_role_name: "invoiceninja"
invoiceninja_root_dir: "{{ project_root_dir }}/{{ invoiceninja_role_name }}"

invoiceninja_web_url: "{{ invoiceninja_role_name }}.{{ traefik_domain }}"
invoiceninja_app_key: "{{ vault_invoiceninja_app_key }}"
invoiceninja_app_env: "production"
invoiceninja_app_debug: false

invoiceninja_db_port: 3306
invoiceninja_db_name: "invoiceninja_db"
invoiceninja_db_user: "{{ vault_invoiceninja_db_user }}"
invoiceninja_db_password: "{{ vault_invoiceninja_db_password }}"

invoiceninja_initial_user_email: "{{ vault_invoiceninja_initial_user_email }}"
invoiceninja_initial_user_password: "{{ vault_invoiceninja_initial_user_password }}"

invoiceninja_smtp_host: "{{ smtp_host }}"
invoiceninja_smtp_port: "{{ smtp_port }}"
invoiceninja_smtp_username: "{{ smtp_user }}"
invoiceninja_smtp_password: "{{ smtp_password }}"
invoiceninja_smtp_encryption: "null"
invoiceninja_smtp_send_from_address: "factures@remydubois.fr"
invoiceninja_smtp_send_from_name: "Facturation SysGrid Solutions"

invoiceninja_reverse_proxy_network: "{{ traefik_network }}"
