---
- name: Restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Restart Network
  ansible.builtin.service:
    name: networking
    state: restarted
  when: ansible_virtualization_type != 'docker'

- name: Create Crowdsec enrollment marker
  ansible.builtin.file:
    path: /etc/crowdsec/console-enrolled
    state: touch
    mode: "0644"

- name: Restart Crowdsec
  ansible.builtin.service:
    name: crowdsec
    state: restarted
