---
- name: Create portainer data directory
  ansible.builtin.file:
    path: "{{ portainer_root_dir }}/data"
    state: directory
    mode: '0755'

- name: Copy portainer docker compose template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ portainer_root_dir }}/docker-compose.yml"
    mode: '0644'

- name: Start portainer compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ portainer_root_dir }}"
    pull: always
    state: present
