---

- name: Create application directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "/opt/talos/{{ role_name }}"
    - "/opt/talos/{{ role_name }}/src"
    - "/opt/talos/{{ role_name }}/config"
    - "/opt/talos/{{ role_name }}/db_data"

- name: Copy docker-compose and php.ini template
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop:
    - { src: docker-compose.yml.j2, dest: "/opt/talos/{{ role_name }}/docker-compose.yml" }
    - { src: php.ini.j2, dest: "/opt/talos/{{ role_name }}/config/php.ini" }


- name: Start docker-compose stack
  community.docker.docker_compose_v2:
    project_src: "/opt/talos/{{ role_name }}"
    state: present
    pull: always
