---
- name: Kernel Hardening
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/99-hardening.conf
    state: present
    reload: true
  loop: "{{ common_sysctl_params }}"
  when: ansible_virtualization_type != 'docker'
