---

- name: Download Tailscale gpg key
  ansible.builtin.get_url:
    url: "https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg"
    checksum: "sha256:3e03dacf222698c60b8e2f990b809ca1b3e104de127767864284e6c228f1fb39"
    dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
    mode: "0644"
  changed_when: false

- name: Add tailscale repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/debian bookworm main"
    state: present

- name: Install Tailscale package
  ansible.builtin.apt:
    name: tailscale
    state: present
    update_cache: true

- name: Start and Enable Tailscale service
  ansible.builtin.service:
    name: tailscaled
    state: started
    enabled: true

- name: Fetch Tailscale status
  ansible.builtin.command: tailscale status --json
  changed_when: false
  register: common_tailscale_status

- name: Parse status JSON
  vars:
    common_tailscale_status_parsed: "{{ common_tailscale_status.stdout | from_json }}"
  ansible.builtin.set_fact:
    common_tailscale_is_online: "{{ common_tailscale_status_parsed.BackendState | default('') == 'Running' }}"

- name: Up tailscale
  ansible.builtin.command:
    cmd: tailscale up --authkey="{{ vault_tailscale_auth_key }}"
  no_log: true
  when: not common_tailscale_is_online
  changed_when: false
