---

- name: Install ufw package
  ansible.builtin.package:
    name: ufw
    state: present

- name: Configure default policy
  community.general.ufw:
    default: deny
    direction: incoming

- name: Allow everything on Loopback
  community.general.ufw:
    rule: allow
    interface: lo
    direction: in

- name: Open SSH + WEB ports
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.protocol | default('tcp') }}"
  loop:
    - { port: "{{ common_http_port }}" }
    - { port: "{{ common_https_port }}" }
    - { port: "{{ tailscale_p2p_port }}", protocol: "udp" }
    - { port: "{{ satisfactory_game_port }}" }
    - { port: "{{ satisfactory_game_port }}", protocol: "udp" }
    - { port: "{{ satisfactory_messaging_port }}" }
    - { port: "{{ ark_fjordur_game_client_port }}", protocol: "udp" }
    - { port: "{{ ark_fjordur_udp_socket_port }}", protocol: "udp" }
    - { port: "{{ ark_fjordur_rcon_port }}"}
    - { port: "{{ ark_fjordur_server_list_port }}", protocol: "udp" }

- name: Open SSH port globally (Safety first for bootstrap)
  community.general.ufw:
    rule: allow
    port: "{{ common_target_ssh_port }}"
    proto: tcp
  when: ansible_facts["tailscale0"] is not defined

- name: Allow SSH on private Vagrant network (DEV ONLY)
  community.general.ufw:
    rule: allow
    src: 192.168.100.0/24
    port: "{{ common_target_ssh_port }}"
    proto: tcp
  when: target_env | default('dev') == 'dev'

- name: Set enable UFW
  community.general.ufw:
    state: enabled
