---
- name: Install ufw package
  ansible.builtin.package:
    name: ufw
    state: present

- name: Allow everything on Loopback
  community.general.ufw:
    rule: allow
    interface: lo
    direction: in

- name: Allow Docker networks to reach Crowdsec LAPI
  community.general.ufw:
    rule: allow
    src: 172.16.0.0/12
    port: 8080
    proto: tcp

- name: UFW - Open application ports
  community.general.ufw:
    rule: allow
    port: "{{ item.port | string }}"
    proto: "{{ item.proto | default('tcp') }}"
    comment: "{{ item.comment | default('Managed by Talos') }}"
  loop: "{{ common_ufw_rules_base + common_ufw_rules_extra }}"

- name: Open SSH port globally (Safety first for bootstrap)
  community.general.ufw:
    rule: allow
    port: "{{ common_target_ssh_port | string }}"
    proto: tcp
  when: ansible_facts["tailscale0"] is not defined

- name: Allow SSH on private Vagrant network (DEV ONLY)
  community.general.ufw:
    rule: allow
    src: 192.168.100.0/24
    port: "{{ common_target_ssh_port | string }}"
  when: target_env == 'dev'

- name: Allow SSH from Tailscale interface
  community.general.ufw:
    rule: allow
    interface: tailscale0
    direction: in
    port: "{{ common_target_ssh_port | string }}"
    proto: tcp
  when: ansible_facts["tailscale0"] is defined

- name: UFW - Enforce default deny policy and enable
  community.general.ufw:
    state: enabled
    policy: deny
    direction: incoming
