---
- name: Create target user group
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ common_target_user }}"
    - "{{ runner_user }}"

- name: Create docker group
  ansible.builtin.group:
    name: "{{ common_docker_group_name }}"
    state: present

- name: Remove default user
  ansible.builtin.user:
    name: "{{ common_default_user }}"
    state: absent
    force: true
  when: remove_default_user

- name: Create target user
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: present
    password: "{{ item.password }}"
    group: "{{ common_target_user }}"
    groups: "{{ item.groups | default('') }}"
    shell: /bin/bash
  loop:
    - name: "{{ common_target_user }}"
      password: "{{ common_target_password_hash }}"
      group: "{{ common_target_user }}"
      groups: "{{ common_docker_group_name }}"
    - name: "{{ runner_user }}"
      password: "!"
      group: "{{ runner_user }}"

- name: Transfer Vault Password to Runner securely
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../.vault_pass_prod"
    dest: "/home/{{ runner_user }}/.vault_pass_prod"
    owner: "{{ runner_user }}"
    group: "{{ runner_user }}"
    mode: "0400"
  when: ansible_connection != 'local'

- name: Set authorized ssh key for target user
  ansible.posix.authorized_key:
    key: "{{ common_target_ssh_pubkey }}"
    user: "{{ common_target_user }}"
    state: present
    exclusive: true
  when: ansible_connection != 'local'

- name: Nopasswd sudo with user
  ansible.builtin.lineinfile:
    path: "{{ item.path }}"
    state: present
    line: "{{ item.line }}"
    mode: "0440"
    create: true
    validate: /usr/sbin/visudo -cf %s
  loop:
    - { path: "/etc/sudoers.d/{{ common_target_user }}", line: "{{ common_target_user }} ALL=(ALL) NOPASSWD: ALL" }
    - { path: "/etc/sudoers.d/{{ runner_user }}", line: "{{ runner_user }} ALL=(ALL) NOPASSWD: ALL" }

- name: Lock root account
  ansible.builtin.user:
    name: root
    password_lock: true
