---
observability_stack_state: "present" # present | stopped | absent
observability_prometheus_image: ""
observability_prometheus_image_tag: ""
observability_alertmanager_image: ""
observability_alertmanager_image_tag: ""
observability_grafana_image: ""
observability_grafana_image_tag: ""
observability_node_exporter_image: ""
observability_node_exporter_image_tag: ""
observability_cadvisor_image: ""
observability_cadvisor_image_tag: ""
observability_loki_image: ""
observability_loki_image_tag: ""
observability_promtail_image: ""
observability_promtail_image_tag: ""
observability_grafana_domain: "grafana.{{ traefik_domain }}"
observability_grafana_admin_user: "sentinel"
observability_grafana_admin_password: "{{ vault_observability_grafana_admin_password }}"
observability_alertmanager_webhook_url: "{{ vault_observability_alertmanager_webhook_url }}"

observability_role_name: "observability"
observability_reverse_proxy_network: "{{ traefik_network }}"
observability_root_dir: "{{ project_root_dir }}/{{ observability_role_name }}"
