---
- name: "Install base system packages"
  ansible.builtin.import_tasks: subtasks/packages.yml
  tags: setup_packages

- name: "Set System Hostname"
  ansible.builtin.import_tasks: subtasks/hostname.yml
  tags: setup_hostname

- name: "Configure NTP (Time Sync)"
  ansible.builtin.import_tasks: subtasks/ntp.yml
  tags: setup_ntp

- name: "Setup users & groups"
  ansible.builtin.import_tasks: subtasks/users.yml
  tags: setup_users

- name: "Install Tailscale"
  ansible.builtin.import_tasks: subtasks/tailscale.yml
  tags: tailscale

- name: "Configure sshd service"
  ansible.builtin.import_tasks: subtasks/sshd.yml
  tags: setup_sshd

- name: "Configure UFW firewall"
  ansible.builtin.import_tasks: subtasks/ufw.yml
  tags: setup_ufw

- name: "Configure CrowdSec IPS"
  ansible.builtin.import_tasks: subtasks/crowdsec.yml
  tags: setup_crowdsec

- name: "SU cmd rules"
  ansible.builtin.import_tasks: subtasks/pamd.yml
  tags: setup_pamd

- name: "Sysctl hardening"
  ansible.builtin.import_tasks: subtasks/sysctl.yml
  tags: sysctl_hardening

- name: "System hardening"
  ansible.builtin.import_tasks: subtasks/hardening.yml
  tags: system_hardening

- name: "Setup ansible-venv"
  ansible.builtin.import_tasks: subtasks/ansible-venv.yml
  tags: ansible-venv

- name: "Final UFW Lockdown"
  ansible.builtin.import_tasks: subtasks/ufw_lockdown.yml
  tags: setup_ufw
