---
sparkyfitness_app_image_tag: "v0.16.5.8"
sparkyfitness_nginx_image_tag: "v0.16.5.8"
sparkyfitness_postgres_image_tag: "18.3-alpine"
sparkyfitness_role_name: "sparkyfitness"
sparkyfitness_root_dir: "{{ project_root_dir }}/{{ sparkyfitness_role_name }}"
sparkyfitness_reverse_proxy_network: "{{ traefik_network }}"
sparkyfitness_web_url: "{{ sparkyfitness_role_name }}.{{ traefik_domain }}"

sparkyfitness_node_env: "production"
sparkyfitness_log_level: "INFO"
sparkyfitness_time_zone: "Europe/Paris"
sparkyfitness_puid: "1000"
sparkyfitness_guid: "1000"
sparkyfitness_server_port: "3010"
sparkyfitness_allow_cors: false
sparkyfitness_extra_trusted_origins: ""
sparkyfitness_db_user: "{{ vault_sparkyfitness_db_user }}"
sparkyfitness_db_host: "{{ sparkyfitness_role_name }}-db"
sparkyfitness_db_name: "{{ sparkyfitness_role_name }}-db"
sparkyfitness_db_password: "{{ vault_sparkyfitness_db_password }}"
sparkyfitness_app_db_user: "{{ vault_sparkyfitness_app_db_user }}"
sparkyfitness_app_db_password: "{{ vault_sparkyfitness_app_db_password }}"
sparkyfitness_db_port: "5432"
sparkyfitness_api_encryption_key: "{{ vault_sparkyfitness_api_encryption_key }}"
sparkyfitness_better_auth_secret: "{{ vault_sparkyfitness_better_auth_secret }}"
sparkyfitness_frontend_url: "https://{{ sparkyfitness_web_url }}"
sparkyfitness_disable_signup: true
sparkyfitness_admin_email: "{{ vault_sparkyfitness_admin_email }}"
sparkyfitness_email_host: "{{ smtp_host }}"
sparkyfitness_email_port: "{{ smtp_port }}"
sparkyfitness_email_secure: true
sparkyfitness_email_user: "{{ smtp_user }}"
sparkyfitness_email_password: "{{ smtp_password }}"
sparkyfitness_email_from: "sparkyfitness@remydubois.fr"
