---
- name: Security hardening
  hosts: all
  become: true

  vars_files:
    - ../group_vars/all/all.yml

  roles:
    - role: common
      tags: common

    - role: hotfix_cve_2026_31431
      tags: hotfix_copyfail
