---
- name: Infrastructure services
  hosts: all
  become: true

  vars_files:
    - ../group_vars/all/all.yml

  roles:
    - role: traefik
      tags: traefik

    - role: portainer
      tags: portainer

    - role: observability
      tags: observability

    - role: redxops.kopia
      tags: kopia
