name: ARK Selective Deploy

permissions:
  contents: read

on:
  push:
    branches: ["ark-live"]

jobs:
  deploy_ark:
    name: Selective ARK Deployment
    runs-on: [self-hosted, prod]
    env:
      ANSIBLE_BIN_PATH: /opt/talos/ansible-venv/bin
      ANSIBLE_FORCE_COLOR: "True"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Dependencies
        run: $ANSIBLE_BIN_PATH/ansible-galaxy install -r requirements.yml --force

      - name: Run ARK Targeted Deployment
        run: |
          $ANSIBLE_BIN_PATH/ansible-playbook site.yml \
          -i inventories/prod/hosts.yml \
          --connection=local \
          --tags ark \
          --vault-id prod@/home/github-runner/.vault_pass_prod

  summary:
    name: Generate ARK Deploy Summary
    needs: deploy_ark
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Write Summary
        run: |
          echo "### Rapport de Déploiement Sélectif ARK" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Étape | Statut |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY

          if [ "${{ needs.deploy_ark.result }}" = "success" ]; then
            echo "| Déploiement Sélectif ARK | ✅ Success |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| Déploiement Sélectif ARK | ❌ Failed |" >> $GITHUB_STEP_SUMMARY
          fi
