name: ARK Selective Deploy

permissions:
  contents: read

on:
  push:
    branches: ["ark-live"]

jobs:
  deploy_ark:
    name: Selective ARK Deployment
    runs-on: [self-hosted, prod]
    env:
      ANSIBLE_BIN_PATH: /opt/talos/ansible-venv/bin

    steps:
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install Dependencies
        run: $ANSIBLE_BIN_PATH/ansible-galaxy install -r requirements.yml --force

      - name: Run ARK Targeted Deployment
        run: |
          $ANSIBLE_BIN_PATH/ansible-playbook site.yml \
          -i inventories/prod/hosts.yml \
          --connection=local \
          --tags ark \
          --vault-id prod@/home/github-runner/.vault_pass_prod
