name: CD
run-name: Deployment of ${{ github.ref_name }} on production server

permissions:
  contents: read

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "roles/ark-server/vars/main.yml"

jobs:
  deploy_production:
    name: Deploy production
    environment: talos-srv
    runs-on: [self-hosted, prod]
    env:
      ANSIBLE_BIN_PATH: /opt/talos/ansible-venv/bin
      ANSIBLE_FORCE_COLOR: "True"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install Dependencies
        run: $ANSIBLE_BIN_PATH/ansible-galaxy install -r requirements.yml --force

      - name: Run Deployment
        run: $ANSIBLE_BIN_PATH/ansible-playbook site.yml -i inventories/prod/hosts.yml --connection=local --vault-id prod@/home/github-runner/.vault_pass_prod
        env:
          ANSIBLE_VAULT_IDENTITY_LIST: ""

  summary:
    name: Generate Deployment Summary
    needs: deploy_production
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Write Summary
        run: |
          echo "### Rapport de Déploiement Production" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Étape | Statut |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY

          if [ "${{ needs.deploy_production.result }}" = "success" ]; then
            echo "| 🚀 Déploiement Production | ✅ Success |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| 🚀 Déploiement Production | ❌ Failed |" >> $GITHUB_STEP_SUMMARY
          fi
