name: Maintenance
run-name: TALOS automated maintenance

permissions:
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 0"
      timezone: "Europe/Paris"
jobs:
  run_maintenance:
    name: Run automated server maintenance
    runs-on: [self-hosted, prod]
    env:
      ANSIBLE_BIN_PATH: /opt/talos/ansible-venv/bin
      ANSIBLE_FORCE_COLOR: "True"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Dependencies
        run: $ANSIBLE_BIN_PATH/ansible-galaxy install -r requirements.yml --force

      - name: Run Maintenance
        run: $ANSIBLE_BIN_PATH/ansible-playbook playbooks/05_maintenance.yml -i inventories/prod/hosts.yml --connection=local --vault-id prod@/home/github-runner/.vault_pass_prod

  summary:
    name: Generate Maintenance Summary
    needs: run_maintenance
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Write Summary
        run: |
          echo "### Rapport de Maintenance Automatisée" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Étape | Statut |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY

          if [ "${{ needs.run_maintenance.result }}" = "success" ]; then
            echo "| Maintenance Automatisée | ✅ Success |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| Maintenance Automatisée | ❌ Failed |" >> $GITHUB_STEP_SUMMARY
          fi
