name: Reboot Server
run-name: Forced reboot of talos-srv executed by Ansible

permissions:
  contents: read

on:
  workflow_dispatch:

env:
  ANSIBLE_BIN_PATH: /opt/talos/ansible-venv/bin
  ANSIBLE_FORCE_COLOR: "True"

jobs:
  reboot_talos_srv:
    name: Reboot the server
    runs-on: [self-hosted, prod]
    environment: talos-srv

    steps:
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install Dependencies
        run: $ANSIBLE_BIN_PATH/ansible-galaxy install -r requirements.yml --force

      - name: Run Reboot
        run: $ANSIBLE_BIN_PATH/ansible-playbook playbooks/05_maintenance.yml --tags reboot -e "maintenance_force_reboot=true maintenance_with_cicd=true" -i inventories/prod/hosts.yml --connection=local --vault-id prod@/home/github-runner/.vault_pass_prod
  wait_server_reboot:
    name: Wait for the server to reboot
    runs-on: ubuntu-24.04
    needs: reboot_talos_srv

    steps:
      - name: Waiting 5 minutes
        run: sleep 300

  verify_server_health:
    name: Verify if server and Docker containers are healthy
    runs-on: [self-hosted, prod]
    needs: wait_server_reboot

    steps:
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install Dependencies
        run: $ANSIBLE_BIN_PATH/ansible-galaxy install -r requirements.yml --force

      - name: Run Healthcheck
        run: $ANSIBLE_BIN_PATH/ansible-playbook playbooks/05_maintenance.yml --tags healthcheck -i inventories/prod/hosts.yml --connection=local --vault-id prod@/home/github-runner/.vault_pass_prod

  summary:
    name: Generate Reboot Summary
    needs: [reboot_talos_srv, wait_server_reboot, verify_server_health]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Write Summary
        run: |
          echo "### Rapport de Redémarrage Serveur" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Étape | Statut |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY

          if [ "${{ needs.reboot_talos_srv.result }}" = "success" ]; then
            echo "| Redémarrage Serveur | ✅ Success |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| Redémarrage Serveur | ❌ Failed |" >> $GITHUB_STEP_SUMMARY
          fi

          if [ "${{ needs.wait_server_reboot.result }}" = "success" ]; then
            echo "| Attente Redémarrage | ✅ Success |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| Attente Redémarrage | ❌ Failed |" >> $GITHUB_STEP_SUMMARY
          fi

          if [ "${{ needs.verify_server_health.result }}" = "success" ]; then
            echo "| Healthcheck | ✅ Success |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| Healthcheck | ❌ Failed |" >> $GITHUB_STEP_SUMMARY
          fi
